'use client';
import {useEffect,useRef,useState} from 'react';
import {useLanguage} from './language';
import './context-demo.css';

const scenes=[
 {duration:6500,title:['One simple task','งานง่าย ๆ หนึ่งอย่าง'],speech:['Please write a reminder for my appointment.','ช่วยเขียนข้อความเตือนนัดหมายให้หน่อยครับ'],caption:['Watch how the same task changes when distracting information piles up.','มาดูกันว่างานเดิมจะเปลี่ยนไปอย่างไร เมื่อมีข้อมูลรบกวนเพิ่มเข้ามา'],clutter:0},
 {duration:7500,title:['Only the information Kubo needs','ให้เฉพาะข้อมูลที่ Kubo ต้องใช้'],speech:['Tomorrow, 10:00, reception B. Got it!','พรุ่งนี้ 10.00 น. ห้องต้อนรับ B เข้าใจแล้วครับ!'],caption:['The green document contains the correct appointment.','เอกสารสีเขียวบอกเวลานัดหมายที่ถูกต้อง'],clutter:0},
 {duration:7500,title:['A clear answer','คำตอบชัดเจน'],speech:['Reminder: your appointment is tomorrow at 10:00 at reception B.','เตือนนัดหมาย: พรุ่งนี้เวลา 10.00 น. ที่ห้องต้อนรับ B ครับ'],caption:['Useful information helps Kubo answer the task.','ข้อมูลที่เกี่ยวข้องช่วยให้ Kubo ตอบได้ตรงงาน'],clutter:0},
 {duration:8500,title:['Now extra information piles up','ลองเพิ่มข้อมูลรบกวน'],speech:['Old appointments… lunch menus… parking notes…','นัดหมายเก่า… เมนูอาหาร… บันทึกเรื่องที่จอดรถ…'],caption:['The correct appointment stays on the desk. We are adding clutter, not changing the task.','ข้อมูลนัดหมายที่ถูกต้องยังอยู่บนโต๊ะ งานยังเหมือนเดิม แต่มีข้อมูลรบกวนเพิ่มเข้ามา'],clutter:3},
 {duration:8500,title:['The answer gets mixed up','คำตอบเริ่มปนกัน'],speech:['Your appointment is at 09:00… or was it 10:00? Reception A or B?','นัดเวลา 09.00 น.… หรือ 10.00 น.? ห้องต้อนรับ A หรือ B นะ?'],caption:['Old and conflicting details can make the useful information harder to use—even while it is still present.','ข้อมูลเก่าและข้อมูลที่ขัดแย้งกันอาจทำให้ใช้ข้อมูลสำคัญได้ยากขึ้น แม้ข้อมูลที่ถูกต้องจะยังอยู่'],clutter:3},
 {duration:6500,title:['Clear away the distractions','นำข้อมูลรบกวนออก'],speech:['Let’s keep only what this task needs.','เก็บไว้เฉพาะข้อมูลที่ต้องใช้ในงานนี้ดีกว่าครับ'],caption:['The task and the correct appointment have not changed.','งานและข้อมูลนัดหมายที่ถูกต้องยังเหมือนเดิม'],clutter:0},
 {duration:8000,title:['The answer is clear again','คำตอบกลับมาชัดเจน'],speech:['Reminder: your appointment is tomorrow at 10:00 at reception B.','เตือนนัดหมาย: พรุ่งนี้เวลา 10.00 น. ที่ห้องต้อนรับ B ครับ'],caption:['Less distracting context. The same correct information.','ข้อมูลรบกวนน้อยลง ใช้ข้อมูลที่ถูกต้องชุดเดิม'],clutter:0},
 {duration:0,title:['This illustrates context rot','นี่คือตัวอย่างของ Context Rot'],speech:['More information does not always mean a better answer.','ข้อมูลมากขึ้น ไม่ได้ทำให้คำตอบดีขึ้นเสมอไป'],caption:['Irrelevant, old or conflicting information can reduce answer quality, even when the right information is still available.','ข้อมูลที่ไม่เกี่ยวข้อง ข้อมูลเก่า หรือข้อมูลที่ขัดแย้งกัน อาจทำให้คำตอบแย่ลง แม้ข้อมูลที่ถูกต้องจะยังอยู่'],clutter:0},
];
export default function ContextDemo(){
 const {language}=useLanguage(),i=language==='th'?1:0,t=(en:string,th:string)=>i?th:en;
 const [step,setStep]=useState(0),[paused,setPaused]=useState(false),[ready,setReady]=useState(false),[failed,setFailed]=useState(false),[reduced,setReduced]=useState(false),[run,setRun]=useState(0),[shownClutter,setShownClutter]=useState(0);
 const host=useRef<HTMLDivElement>(null),api=useRef<any>(null),elapsed=useRef(0),phase=scenes[step];
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>{setReduced(mq.matches);if(mq.matches)setPaused(true);};change();mq.addEventListener('change',change);return()=>mq.removeEventListener('change',change);},[]);
 useEffect(()=>{let disposed=false,local:any;import('./desk-scene.mjs').then(m=>m.createDesk(host.current,{intro:true,demonstration:true})).then(a=>{local=a;if(disposed)a.dispose();else{api.current=a;setReady(true);}}).catch(()=>{if(!disposed)setFailed(true);});return()=>{disposed=true;local?.dispose();api.current=null;};},[]);
 useEffect(()=>{elapsed.current=0;},[step,run]);
 useEffect(()=>{if((!ready&&!failed)||paused||step===scenes.length-1)return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now();if(!document.hidden){elapsed.current+=Math.min(now-last,150);if(elapsed.current>=phase.duration)setStep(s=>Math.min(s+1,scenes.length-1));}last=now;},100);return()=>clearInterval(timer);},[ready,failed,paused,step,run]);
 useEffect(()=>{if(step===0){api.current?.closeUp();setShownClutter(0);}else{api.current?.reveal();if(step===3)setShownClutter(0);else if(step!==5)setShownClutter(phase.clutter);}},[step,ready,run]);
 useEffect(()=>{if(paused||(!ready&&!failed)||![3,5].includes(step))return;const timer=setInterval(()=>{if(!document.hidden)setShownClutter(n=>step===3?Math.min(3,n+1):Math.max(0,n-1));},1200);return()=>clearInterval(timer);},[step,paused,ready,failed,run]);
 useEffect(()=>{const cards=step===0?[]:[{id:'correct',cost:1},...Array.from({length:shownClutter},(_,n)=>({id:'clutter-'+n,cost:2}))];api.current?.setCards(cards);api.current?.setMood(step===4?'confused':'ready');},[step,shownClutter,ready,run]);
 useEffect(()=>{api.current?.setPaused(paused);},[paused,ready]);
 function replay(){setStep(0);setShownClutter(0);setRun(n=>n+1);setPaused(reduced);}
 return <main className="context-demo" data-step={step}><header><span>QI-01 · CONTEXT ROT</span><h1>{t('When extra information gets in the way','เมื่อข้อมูลรบกวน AI')}</h1><p>{t('A short animated explanation. Just watch Kubo.','ภาพเคลื่อนไหวสั้น ๆ ดู Kubo แล้วเรียนรู้ไปด้วยกัน')}</p></header>
 <section className={'context-stage '+(step===4?'is-confused':'')} aria-label={t('Context rot demonstration','ภาพสาธิต Context Rot')}><div ref={host} className="context-canvas" role="img" aria-label={t('Kubo’s desk fills with distracting documents, then clears','โต๊ะของ Kubo มีเอกสารรบกวนเพิ่มขึ้น แล้วถูกจัดให้โล่งอีกครั้ง')}/><div className="context-speech" aria-live="polite"><small>{phase.title[i]}</small><p>{phase.speech[i]}</p></div>
 {step>0&&<div className="context-evidence"><div className="correct-note"><strong>{t('Correct information · still here','ข้อมูลที่ถูกต้อง · ยังอยู่ที่เดิม')}</strong><span>{t('Tomorrow · 10:00 · Reception B','พรุ่งนี้ · 10.00 น. · ห้องต้อนรับ B')}</span></div>{shownClutter>0&&<div className="clutter-note"><strong>{t('Distracting information','ข้อมูลรบกวน')}</strong><span>{[t('Old appointment: 09:00, reception A','นัดหมายเก่า: 09.00 น. ห้องต้อนรับ A'),t('Lunch menus','เมนูอาหาร'),t('Parking notes','บันทึกเรื่องที่จอดรถ')].slice(0,shownClutter).join(' · ')}</span></div>}</div>}</section>
 <div className="context-caption" aria-live="polite">{phase.caption[i]}</div><div className="context-playback"><span>{step+1} / {scenes.length}</span><button onClick={()=>setPaused(v=>!v)} disabled={step===scenes.length-1}>{paused?t('Play','เล่นต่อ'):t('Pause','หยุดชั่วคราว')}</button><button onClick={replay}>{t('Replay demonstration','ดูภาพสาธิตอีกครั้ง')}</button>{(paused||reduced)&&step<scenes.length-1&&<button onClick={()=>setStep(s=>s+1)}>{t('Next scene','ฉากถัดไป')}</button>}</div>
 <p className="context-footnote">{failed?t('The 3D scene is unavailable; the illustrated explanation continues in text.','ฉาก 3 มิติยังไม่พร้อม แต่ยังอ่านคำอธิบายตามลำดับได้'):!ready?t('Preparing Kubo…','กำลังเตรียม Kubo…'):t('Illustration, not a real AI response. Extra context does not always cause errors.','ภาพจำลองเพื่ออธิบาย ไม่ใช่คำตอบจาก AI จริง ข้อมูลเพิ่มขึ้นไม่ได้ทำให้ผิดทุกครั้ง')}</p></main>;
}
