'use client';
import {useEffect,useRef,useState} from 'react';
import {useLanguage} from './language';
import {Button} from '@/components/ui/button';
import {KPI_CARDS,QUESTION,evaluateKpi} from './kpi-lesson.mjs';
export default function DeskLesson(){
 const {language}=useLanguage(),i=language==='th'?1:0,txt=(en:string,th:string)=>i?th:en;
 const host=useRef<HTMLDivElement>(null),scene=useRef<any>(null),current=useRef<string[]>([]);
 const [ids,setIds]=useState<string[]>([]),[result,setResult]=useState<any>(null),[error,setError]=useState(false);
 const cards=KPI_CARDS.filter(c=>ids.includes(c.id)),tokens=cards.reduce((n,c)=>n+c.tokens,0);
 useEffect(()=>{let stopped=false,api:any;import('./desk-scene.mjs').then(m=>m.createDesk(host.current)).then(a=>{api=a;if(stopped)a.dispose();else{scene.current=a;a.setCards(KPI_CARDS.filter(c=>current.current.includes(c.id)));}}).catch(()=>setError(true));return()=>{stopped=true;scene.current=null;api?.dispose();};},[]);
 useEffect(()=>{current.current=ids;scene.current?.setCards(cards);},[ids]);
 function toggle(id:string){setIds(list=>list.includes(id)?list.filter(x=>x!==id):[...list,id]);setResult(null);}
 return <main className="desk-lesson"><header className="lesson-heading"><div><p>QI-01 · {txt('THE AGENT’S DESK','โต๊ะของเอเจนต์')}</p><h1>{txt('What should Kubo know?','Kubo ควรรู้อะไรบ้าง?')}</h1><span>{QUESTION[i]}</span></div><span className="simulation-tag">{txt('Teaching simulation · synthetic hospital records','แบบจำลองเพื่อการเรียนรู้ · ข้อมูลโรงพยาบาลสมมติ')}</span></header>
 <div className="lesson-grid"><section className="desk-visual"><div ref={host} className="desk-canvas" role="img" aria-label={txt('Kubo and a desk of selected documents','Kubo และโต๊ะที่วางเอกสารที่เลือก')}/><div className="desk-bubble" aria-live="polite">{result?result.answer[i]:txt('Help me choose the information I need.','ช่วยเลือกข้อมูลที่ผมต้องใช้หน่อยครับ')}</div>{error&&<p>{txt('The scene could not load. The exercise below still works.','ฉากโหลดไม่ได้ แต่ยังทำกิจกรรมด้านล่างได้')}</p>}<div className="desk-tray"><strong>{txt('On the desk','บนโต๊ะตอนนี้')}</strong><div>{cards.length?cards.map(c=><button key={c.id} onClick={()=>toggle(c.id)}>{c.title[i]} ×</button>):txt('Choose documents from the collection.','เลือกเอกสารจากรายการ')}</div></div></section>
 <section className="lesson-controls"><div className="desk-capacity"><strong>{txt('Working space','พื้นที่ทำงาน')}</strong><span>{tokens.toLocaleString('en-US')} / 1,000 {txt('illustrative tokens','โทเคนโดยประมาณ')}</span><meter min={0} max={1000} value={Math.min(tokens,1000)}/><small>{tokens>1000?txt('Over capacity in this teaching model. Remove unnecessary documents.','เกินพื้นที่ในแบบจำลองนี้ ลองนำเอกสารที่ไม่จำเป็นออก'):txt('These token weights illustrate context limits; they are not measured model usage.','น้ำหนักโทเคนใช้สาธิตขีดจำกัด ไม่ใช่จำนวนที่วัดจากโมเดลจริง')}</small></div>
 <div className="lesson-cards">{KPI_CARDS.map(c=><button key={c.id} className="lesson-card" aria-pressed={ids.includes(c.id)} onClick={()=>toggle(c.id)}><span><strong>{c.title[i]}</strong><small>{c.tokens} tok · {ids.includes(c.id)?txt('remove','นำออก'):txt('add','เพิ่ม')}</small></span><p>{c.text[i]}</p></button>)}</div><div className="lesson-actions"><Button onClick={()=>setResult(evaluateKpi(ids))}>{txt('Ask Kubo','ถาม Kubo')}</Button><Button variant="outline" onClick={()=>{setIds([]);setResult(null);}}>{txt('Reset','เริ่มใหม่')}</Button></div></section></div>
 <section className="lesson-explanation" aria-live="polite"><h2>{txt('What changed his answer?','อะไรทำให้คำตอบเปลี่ยน?')}</h2><p>{result?result.why[i]:txt('Start with the current data and formula. Ask Kubo, then add distracting documents and compare.','เริ่มจากข้อมูลปัจจุบันและสูตร ถาม Kubo แล้วเพิ่มเอกสารรบกวนเพื่อเปรียบเทียบ')}</p><small>{txt('All rates are fictional. Answers follow fixed teaching rules, not a real AI. This illustrates context rot; real models do not always make these mistakes.','อัตราทั้งหมดเป็นข้อมูลสมมติ คำตอบใช้กติกาที่กำหนดไว้ ไม่ใช่ AI จริง ใช้สาธิต context rot โมเดลจริงไม่ได้ผิดแบบนี้ทุกครั้ง')}</small></section></main>;
}
