'use client';
import {useEffect,useRef,useState,lazy,Suspense} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,CheckCheck,ClipboardList,PenLine,CalendarDays,Clock3,MapPin,Ticket,Compass,Download,FileCode2,Fullscreen,Grid2X2,Home,Search,ShieldCheck,TriangleAlert,X,RotateCcw,Users,Workflow} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {LanguageProvider,LanguageSwitch,useLanguage} from './language';
import {CHAPTERS,SLIDES,ROLES,c,type Copy,type Role,type Slide} from './orchestration-content';
import './orchestration.css';
const Office=lazy(()=>import('./legacy-presentation').then(m=>({default:m.Workspace})));
const Tokens=lazy(()=>import('./token-lesson'));
const ROLE_ORDER:Role[]=['analyst','writer','checker'];
const ICONS={analyst:Compass,writer:PenLine,checker:ShieldCheck};
const firstSlide=(chapter:number)=>SLIDES.findIndex(s=>s.chapter===chapter);
function useCopy(){const {language}=useLanguage();return (x:Copy)=>x[language==='th'?1:0];}
function Kubo({action='Idle'}:{action?:string}){
 const host=useRef<HTMLElement>(null),api=useRef<{action:(name:string)=>void;dispose:()=>void}|null>(null),latest=useRef(action),[failed,setFailed]=useState(false);
 useEffect(()=>{let stopped=false,runtime:{action:(name:string)=>void;dispose:()=>void}|undefined;import('./orchestration-scene.mjs').then(m=>m.createOrchestrator(host.current)).then(r=>{runtime=r;if(stopped)r.dispose();else{api.current=r;r.action(latest.current);}}).catch(()=>{if(!stopped)setFailed(true);});return()=>{stopped=true;api.current=null;runtime?.dispose();};},[]);
 useEffect(()=>{latest.current=action;api.current?.action(action);},[action]);const t=useCopy();
 return <figure className="or-kubo" ref={host} aria-label={t(c('Kubo, the orchestrator','Kubo ผู้ประสานงาน'))}>{failed&&<div className="or-kubo-fallback"><Workflow/><span>Kubo</span><small>{t(c('Orchestrator','ผู้ประสานงาน'))}</small></div>}</figure>;
}
function AgentCard({agentRole:role,active=false,done=false,muted=false}:{agentRole:Role;active?:boolean;done?:boolean;muted?:boolean}){
 const t=useCopy(),r=ROLES[role],Icon=ICONS[role];
 return <article className={`or-agent agent-${role} ${active?'is-active':''} ${muted?'is-muted':''}`} style={{'--role':r.color} as React.CSSProperties}><span className="or-role-icon"><Icon size={25}/></span><div><strong>{r.name}</strong><p>{t(r.job)}</p></div>{done&&<Check className="or-agent-check" size={18} aria-label={t(c('Completed','เสร็จแล้ว'))}/>}</article>;
}
function Hub({slide}:{slide:Slide}){
 const t=useCopy(),active=slide.active||[],returning=['return','fail','pass'].includes(slide.status||'');
 return <div className={`or-hub status-${slide.status||'idle'}`} aria-label={t(c('Orchestrator and specialist team','ผู้ประสานงานและทีมผู้ช่วย'))}>
  <svg className="or-connections" viewBox="0 0 1000 520" aria-hidden="true" preserveAspectRatio="none">{ROLE_ORDER.map((r,i)=>{const left=i<2,y=i===2?260:i===0?140:380,d=`M 500 260 C ${left?390:610} 260, ${left?340:660} ${y}, ${left?225:775} ${y}`;return <g key={r} style={{'--role':ROLES[r].color} as React.CSSProperties}><path className="or-wire" d={d}/>{active.includes(r)&&<path className={`or-signal ${returning?'returning':''}`} d={d}/>}</g>;})}</svg>
  <div className="or-hub-agents">{ROLE_ORDER.map(r=><AgentCard key={r} agentRole={r} active={active.includes(r)} done={slide.done?.includes(r)}/>)}</div>
  <div className="or-hub-center"><Kubo action={slide.status==='fail'?'Concerned':slide.status==='pass'?'Approved':slide.status==='assign'?'Thinking':'Idle'}/><div className="or-kubo-label"><strong>Kubo</strong><span>ORCHESTRATOR</span></div></div>
  {slide.caption&&<div className={`or-handoff ${slide.status==='fail'?'is-failure':''}`} aria-live="polite"><small>{slide.handoff?t(slide.handoff):slide.role?`${returning?ROLES[slide.role].name:'Kubo'} → ${returning?'Kubo':ROLES[slide.role].name}`:t(c('KUBO ↔ TEAM','KUBO ↔ ทีมผู้ช่วย'))}</small><p>{slide.status==='fail'&&<TriangleAlert size={20}/>} {t(slide.caption)}</p></div>}
 </div>;
}
function EventPreview({finished=false}:{finished?:boolean}){
 const t=useCopy();
 const facts=[
 {icon:CalendarDays,label:c('Date','วัน'),value:c('20 Nov 2026','20 พ.ย. 2026')},
 {icon:Clock3,label:c('Time','เวลา'),value:c('09:00–11:00','09:00–11:00')},
 {icon:MapPin,label:c('Place','สถานที่'),value:c('Room B','ห้อง B')},
 {icon:Ticket,label:c('Fee','ค่าใช้จ่าย'),value:c('Free','ฟรี')},
 ];
 return <article className="or-browser or-event"><div className="or-code-title"><FileCode2 size={19}/><span>{finished?'announcement-v2.md':'event-brief.md'}</span><span className="or-code-badge">{t(c('FICTIONAL EXAMPLE','ตัวอย่างสมมติ'))}</span></div><div className="or-browser-body"><span className="or-eyebrow">{t(c(finished?'PARTICIPANT ANNOUNCEMENT':'ORGANIZER’S BRIEF',finished?'ประกาศสำหรับผู้เข้าร่วม':'บรีฟจากผู้จัด'))}</span><h2>AI Basics</h2><p className="or-event-intro">{t(c(finished?'Join our beginner-friendly AI workshop.':'A workshop for beginners.',finished?'เชิญร่วมเวิร์กช็อป AI สำหรับผู้เริ่มต้น':'เวิร์กช็อปสำหรับผู้เริ่มต้น'))}</p><dl className="or-event-facts">{facts.map(({icon:Icon,label,value},i)=><div key={i}><Icon size={20}/><dt>{t(label)}</dt><dd>{t(value)}</dd></div>)}</dl><div className={`or-event-registration ${finished?'is-confirmed':''}`}>{finished?<Check size={18}/>:<TriangleAlert size={18}/>}<span>{t(c(finished?'No registration required.':'Registration: not specified.',finished?'ไม่ต้องลงทะเบียน':'การลงทะเบียน: ยังไม่ระบุ'))}</span></div></div></article>;
}
function Evidence(){
 const t=useCopy();
 return <div className="or-evidence"><div className="or-evidence-pair"><article><span className="or-eyebrow">{t(c('SOURCE · EVENT BRIEF','ต้นทาง · บรีฟกิจกรรม'))}</span><CalendarDays size={34}/><h2>{t(c('20 Nov 2026','20 พ.ย. 2026'))}</h2><p>event-brief.md</p></article><article className="has-error"><span className="or-eyebrow">{t(c('DRAFT · VERSION 1','ร่าง · รุ่นที่ 1'))}</span><TriangleAlert size={34}/><h2>{t(c('21 Nov 2026','21 พ.ย. 2026'))}</h2><p>{t(c('“Join us on 21 Nov…”','“เชิญร่วมงานวันที่ 21 พ.ย.…”'))}</p></article></div><div className="or-evidence-finding"><ShieldCheck size={24}/><div><strong>Quality Checker → Kubo</strong><p>{t(c('Date mismatch. Ask Writer to use 20 Nov.','วันที่ไม่ตรงต้นทาง ให้ Writer แก้เป็น 20 พ.ย.'))}</p></div></div></div>;
}
function SlideVisual({slide}:{slide:Slide}){
 const t=useCopy();
 if(slide.kind==='hub'||slide.kind==='flow')return <Hub slide={slide}/>;
 if(slide.kind==='office')return <div className="or-office-demo"><Suspense fallback={<p>{t(c('Opening the office…','กำลังเปิดออฟฟิศ…'))}</p>}><Office presentationMode/></Suspense></div>;
 if(slide.kind==='evidence')return <Evidence/>;
 if(slide.kind==='mission')return <div className="or-mission"><div className="or-mission-kubo"><Kubo action={slide.id==='mission'?'Wave':'Thinking'}/><span className="or-bubble">{t(c('Let’s define the job.','มาเริ่มจากโจทย์กัน'))}</span></div><div className="or-mission-example"><EventPreview/>{slide.items&&<div className="or-criteria">{slide.items.map((item,i)=><div key={i}><Check size={18}/><strong>{t(item.label)}</strong><span>{t(item.value)}</span></div>)}</div>}</div></div>;
 if(slide.kind==='roles')return <div className="or-role-board"><div className="or-role-grid">{ROLE_ORDER.map(r=><div key={r}><AgentCard agentRole={r} active/><p className="or-role-boundary">{t(ROLES[r].boundary)}</p></div>)}</div><div className="or-role-foot"><Users size={20}/>{t(c('Reusable roles, selected by the orchestrator.','บทบาทที่ใช้ซ้ำได้ โดย Orchestrator เป็นผู้เลือก'))}</div></div>;
 if(slide.kind==='file'||slide.kind==='setup')return <div className="or-definition"><div className="or-code-window"><div className="or-code-title"><FileCode2 size={20}/><span>{slide.kind==='setup'?slide.id==='save'?t(c('Project structure','โครงสร้างโปรเจกต์')):t(c('Example request','คำสั่งตัวอย่าง')):slide.filename||(slide.role?{analyst:'brief-analyst.md',writer:'announcement-writer.md',checker:'quality-checker.md'}[slide.role]:'orchestrator-instructions.md')}</span><span className="or-code-badge">{t(c('EXAMPLE','ตัวอย่าง'))}</span></div><pre aria-label={t(c('Agent definition example','ตัวอย่างไฟล์กำหนด Agent'))}><code>{slide.code&&t(slide.code)}</code></pre>{slide.caption&&<p className="or-code-caption">{t(slide.caption)}</p>}</div><div className="or-definition-guide">{slide.role?<AgentCard agentRole={slide.role} active/>:<div className="or-guide-label"><Workflow/><strong>{t(c('Orchestrator','ผู้ประสานงาน'))}</strong></div>}<Kubo action={slide.kind==='setup'?'Typing':'ReadScreen'}/></div></div>;
 if(slide.kind==='compare')return <div className="or-comparison">{slide.items?.map((item,i)=>{const Icon=slide.id==='ownership'?[Compass,PenLine,ShieldCheck][i]:[Check,Search,RotateCcw][i];return <article key={i}><span className="or-comparison-number">0{i+1}</span><Icon size={42}/><h2>{t(item.label)}</h2><p>{t(item.value)}</p></article>;})}</div>;
 if(slide.kind==='brief')return <div className="or-brief"><div className="or-brief-heading"><ClipboardList size={34}/><span>{t(c('ASSIGNMENT 01','โจทย์ที่ 01'))}</span><AgentCard agentRole="analyst" active/></div><div className="or-brief-fields">{slide.items?.map((item,i)=><div key={i}><span>{t(item.label)}</span><strong>{t(item.value)}</strong></div>)}</div></div>;
 return <div className="or-finish"><EventPreview finished/><div className="or-delivery"><CheckCheck size={40}/>{slide.items?.map((item,i)=><div key={i}><span>{t(item.label)}</span><strong>{t(item.value)}</strong></div>)}</div></div>;
}
function Presentation(){
 const t=useCopy(),[index,setIndex]=useState(0),[notes,setNotes]=useState(false),[overview,setOverview]=useState(false),[appendix,setAppendix]=useState(''),[fullscreen,setFullscreen]=useState(false);
 const root=useRef<HTMLDivElement>(null),heading=useRef<HTMLHeadingElement>(null),slide=SLIDES[index];
 useEffect(()=>{const sync=()=>{const hash=location.hash.slice(1);if(hash==='workspace'||hash==='tokens'){setAppendix(hash);return;}setAppendix('');const aliases:Record<string,string>={explore:'analyze','explorer-report':'clarify',build:'draft',parallel:'check'};const i=SLIDES.findIndex(s=>(aliases[hash]||hash)===s.id);if(i>=0)setIndex(i);else if(/^qi-0[1-7]$/.test(hash)){const map=['mission','orchestrator','agent-file','choose-team','brief','failure','office-demo'];setIndex(SLIDES.findIndex(s=>s.id===map[Number(hash.slice(-1))-1]));}};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);},[]);
 function go(next:number){const i=Math.max(0,Math.min(SLIDES.length-1,next));setIndex(i);setAppendix('');history.replaceState(null,'',`#${SLIDES[i].id}`);requestAnimationFrame(()=>heading.current?.focus({preventScroll:true}));}
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(notes||overview||appendix||e.altKey||e.ctrlKey||e.metaKey||e.shiftKey)return;const target=e.target as HTMLElement;if(target.closest('input,textarea,select,button,a,summary,canvas,[role="dialog"],[contenteditable="true"]'))return;if(e.key==='ArrowRight'||e.key==='PageDown'||e.key===' '){e.preventDefault();go(index+1);}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(index-1);}if(e.key.toLowerCase()==='n'){e.preventDefault();setNotes(true);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[index,notes,overview,appendix]);
 useEffect(()=>{const fn=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',fn);return()=>document.removeEventListener('fullscreenchange',fn);},[]);
 async function toggleFull(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{/* Browser may decline fullscreen; normal navigation remains available. */}}
 return <div className="or-presentation" ref={root}>
  <header className="or-topbar"><a className="or-brand" href="#mission" onClick={e=>{e.preventDefault();go(0);}}><span className="or-brand-icon"><Workflow size={21}/></span><span>Kubo<span className="or-brand-sub"> CLASSROOM</span></span></a><div className="or-topbar-actions"><Button variant="ghost" onClick={()=>setOverview(true)} aria-label={t(c('Chapters','บทเรียน'))}><Grid2X2 size={18}/><span>{t(c('Chapters','บทเรียน'))}</span></Button><LanguageSwitch/><Button variant="ghost" size="icon" onClick={toggleFull} aria-label={t(c(fullscreen?'Exit full screen':'Full screen',fullscreen?'ออกจากเต็มหน้าจอ':'เต็มหน้าจอ'))}><Fullscreen size={19}/></Button></div></header>
  {appendix?<div className="or-appendix"><div className="or-appendix-bar"><Button onClick={()=>go(index)}><ArrowLeft/>{t(c('Back to presentation','กลับสู่การนำเสนอ'))}</Button><span>{t(c('Optional appendix','ภาคผนวกเสริม'))}</span></div><Suspense fallback={<p>{t(c('Opening…','กำลังเปิด…'))}</p>}>{appendix==='workspace'?<Office/>:<Tokens/>}</Suspense></div>:<>
  <nav className="or-chapters" aria-label={t(c('Presentation chapters','บทในการนำเสนอ'))}>{CHAPTERS.map((chapter,i)=><button key={i} onClick={()=>go(firstSlide(i))} aria-current={slide.chapter===i?'step':undefined}><span>{String(i+1).padStart(2,'0')}</span><span>{t(chapter)}</span></button>)}</nav>
  <main className={`or-slide kind-${slide.kind}`} data-slide={slide.id}><div className="or-slide-heading"><div className="or-kicker"><span>{String(slide.chapter+1).padStart(2,'0')} / {t(CHAPTERS[slide.chapter])}</span><span className="or-demo-label">{t(c('Illustrated demonstration','ภาพจำลองเพื่ออธิบาย'))}</span></div><h1 tabIndex={-1} ref={heading}>{t(slide.title)}</h1><p>{t(slide.line)}</p></div><div className="or-visual"><SlideVisual slide={slide}/></div><div className="or-takeaway"><span className="or-takeaway-mark"/><p>{t(slide.takeaway)}</p></div></main>
  <footer className="or-controls"><div className="or-controls-left"><Button variant="ghost" onClick={()=>setNotes(true)} aria-label={t(c('Presenter notes','บันทึกผู้บรรยาย'))}><BookOpen size={18}/><span>{t(c('Presenter notes','บันทึกผู้บรรยาย'))}</span></Button><span className="or-key-hint">{t(c('← → to navigate','ใช้ ← → เปลี่ยนสไลด์'))}</span></div><div className="or-navigation"><Button variant="outline" size="icon" disabled={index===0} onClick={()=>go(index-1)} aria-label={t(c('Previous slide','สไลด์ก่อนหน้า'))}><ArrowLeft size={20}/></Button><span className="or-slide-count">{String(index+1).padStart(2,'0')} <span>/ {SLIDES.length}</span></span><Button className="or-next" onClick={()=>go(index===SLIDES.length-1?0:index+1)}>{index===SLIDES.length-1?t(c('Restart','เริ่มใหม่')):t(c('Next','ถัดไป'))}<ArrowRight size={18}/></Button></div><div className="or-progress" style={{width:`${(index+1)/SLIDES.length*100}%`}}/></footer></>}
  <Sheet open={notes} onOpenChange={setNotes}><SheetContent className="or-notes" showCloseButton={false}><div className="or-panel-head"><span>{t(c('PRESENTER NOTES','บันทึกผู้บรรยาย'))}</span><Button variant="ghost" size="icon" onClick={()=>setNotes(false)} aria-label={t(c('Close notes','ปิดบันทึก'))}><X/></Button></div><SheetTitle>{t(slide.title)}</SheetTitle><SheetDescription>{t(c('Slide','สไลด์'))} {index+1} · {t(CHAPTERS[slide.chapter])}</SheetDescription><p className="or-notes-text">{t(slide.notes)}</p>{slide.ask&&<div className="or-audience-question"><small>{t(c('ASK THE AUDIENCE','ชวนผู้ฟังคิด'))}</small><p>{t(slide.ask)}</p></div>}<div className="or-notes-bottom"><p>{t(c('The event, draft and check results are fictional teaching examples. Agent files define reusable roles; the brief supplies this task’s facts.','กิจกรรม ร่างประกาศ และผลตรวจเป็นตัวอย่างสมมติ ไฟล์ Agent กำหนดบทบาทที่ใช้ซ้ำ ส่วนบรีฟให้ข้อมูลเฉพาะงาน'))}</p><a href="/agent-examples/presenter-notes.md" download><Download size={16}/>{t(c('All presenter notes','บันทึกผู้บรรยายทั้งหมด'))}</a><a href="https://code.claude.com/docs/en/subagents" target="_blank" rel="noreferrer">{t(c('Claude Code: agent file reference ↗','อ้างอิงไฟล์ Agent ของ Claude Code ↗'))}</a></div></SheetContent></Sheet>
  <Dialog open={overview} onOpenChange={setOverview}><DialogContent className="or-overview" showCloseButton={false}><div className="or-panel-head"><DialogTitle>{t(c('The presentation','เลือกบทเรียน'))}</DialogTitle><Button variant="ghost" size="icon" onClick={()=>setOverview(false)} aria-label={t(c('Close chapters','ปิดรายการบทเรียน'))}><X/></Button></div><DialogDescription>{t(c('One task, from request to verified result.','ติดตามหนึ่งงาน ตั้งแต่คำขอจนถึงผลที่ตรวจแล้ว'))}</DialogDescription><div className="or-chapter-grid">{CHAPTERS.map((chapter,i)=><button key={i} onClick={()=>{go(firstSlide(i));setOverview(false);}}><span>0{i+1}</span><strong>{t(chapter)}</strong><small>{SLIDES.filter(s=>s.chapter===i).length} {t(c('slides','สไลด์'))}</small></button>)}</div><div className="or-appendix-links"><span>{t(c('Optional resources','เอกสารและส่วนเสริม'))}</span><a href="#workspace" onClick={()=>setOverview(false)}><Home size={17}/>{t(c('Explore the office','สำรวจห้องทำงาน'))}</a><a href="#tokens" onClick={()=>setOverview(false)}>{t(c('Token counter','ตัวนับโทเคน'))}</a><a href="/agent-examples/event-agent-kit.zip" download><Download size={17}/>{t(c('Event agent files','ไฟล์ Agent งานประกาศ'))}</a><a href="/agent-examples/course-agent-kit.zip" download>{t(c('Advanced: coding-agent example','ตัวอย่างเสริม: ทีมเขียนโค้ด'))}</a></div></DialogContent></Dialog>
 </div>;
}
export default function OrchestrationPresentation(){return <LanguageProvider><Presentation/></LanguageProvider>;}
