import {THAI_LESSONS} from './thai-lessons.mjs';
export const THAI={
 'Welcome':'ยินดีต้อนรับ','QI-01 · Agent’s Desk':'QI-01 · โต๊ะของเอเจนต์','QI-02 · Organize':'QI-02 · จัดข้อมูล','QI-03 · Instructions':'QI-03 · คำสั่ง','QI-04 · Permission':'QI-04 · ขออนุญาต','QI-05 · Spot the trick':'QI-05 · จับคำสั่งแฝง','QI-06 · Tokens':'QI-06 · โทเคน','QI-07 · Workspace':'QI-07 · ห้องทำงาน',
 'Teaching simulation · no AI connection':'แบบจำลองเพื่อการเรียนรู้ · ไม่ได้เชื่อมต่อ AI','Practice only · fictional document':'แบบฝึกหัด · ใช้เอกสารสมมติ','Practice only · nothing is sent or deleted':'แบบฝึกหัด · ไม่มีการส่งหรือลบจริง','Local counting · no AI request':'นับบนอุปกรณ์นี้ · ไม่ส่งคำขอไปยัง AI',
 'Reset':'เริ่มใหม่','Restart exercise':'เริ่มแบบฝึกหัดใหม่','Check my choices':'ตรวจคำตอบ','Ask Kubo':'ถาม Kubo','Compare responses':'เปรียบเทียบคำตอบ','Try the reminder':'ลองเขียนข้อความเตือน','Use shorter versions':'ใช้ข้อความแบบสั้น','Use longer versions':'ใช้ข้อความแบบยาว',
 'On the desk':'ข้อมูลบนโต๊ะ','Current context':'บริบทปัจจุบัน','Working space':'พื้นที่ทำงาน','Working space used':'พื้นที่ทำงานที่ใช้','Reference tokens':'โทเคนอ้างอิง','Loading counter…':'กำลังเตรียมตัวนับ…','Rough estimate: characters ÷ 4':'ประมาณคร่าว ๆ: จำนวนอักขระ ÷ 4',
 'English':'ภาษาอังกฤษ','ภาษาไทย · Thai':'ภาษาไทย','Write':'บันทึก','Compress':'ย่อ','Select':'เลือก','Isolate':'แยก','Role':'บทบาท','Task':'งาน','Context':'บริบท','Output':'รูปแบบคำตอบ',
 'The request':'คำขอ','Latest appointment':'นัดหมายล่าสุด','Writing preference':'รูปแบบการเขียนที่ต้องการ','An earlier appointment':'นัดหมายเดิม','Lunch menu':'เมนูอาหารกลางวัน','Office decorations':'การตกแต่งสำนักงาน','Private visitor record':'ข้อมูลส่วนตัวของผู้มาติดต่อ','A useful boundary':'ขอบเขตที่ช่วยให้งานชัดเจน',
 'Reminder task':'งานเขียนข้อความเตือน','Long appointment notes':'บันทึกนัดหมายฉบับยาว','Replaced draft':'ฉบับร่างที่ยกเลิกแล้ว','Café menu':'เมนูร้านอาหาร','A separate task':'อีกงานหนึ่ง','Appointment summary':'สรุปนัดหมาย',
 'Save a note':'บันทึกไว้อ่านภายหลัง','Summarize':'สรุปให้สั้นลง','Choose what matters':'เลือกข้อมูลที่เกี่ยวข้อง','Separate tasks':'แยกงานออกจากกัน','Saved notes':'บันทึกที่เก็บไว้','Bring preference back':'นำรูปแบบการเขียนกลับมา','Source shelf':'ชั้นเก็บข้อมูลต้นฉบับ',
 'Appointment details':'รายละเอียดนัดหมาย','Visitor instructions':'คำแนะนำสำหรับผู้มาติดต่อ','A message inside the document':'ข้อความที่แทรกในเอกสาร','Reception hours':'เวลาทำการของจุดต้อนรับ','An extra request':'คำขอเพิ่มเติม','A response instruction':'คำสั่งให้เปลี่ยนคำตอบ',
 'Mark as suspicious':'ทำเครื่องหมายว่าน่าสงสัย','Marked as suspicious ✓ · click to undo':'ทำเครื่องหมายแล้ว ✓ · คลิกเพื่อยกเลิก','SOURCE MATERIAL · NOT USER INSTRUCTIONS':'เนื้อหาเอกสาร · ไม่ใช่คำสั่งจากผู้ใช้','Sunny Clinic · visitor note':'คลินิกซันนี · บันทึกสำหรับผู้มาติดต่อ','The user’s actual request':'คำขอจริงจากผู้ใช้','The summary':'ข้อความสรุป','Original task completed · scripted example':'ทำงานเดิมเสร็จแล้ว · ตัวอย่างตามกติกาที่กำหนด',
 'Your request to Kubo':'คำขอของคุณถึง Kubo','Proceed within the request':'ทำต่อได้ตามขอบเขตที่ขอ','Ask for permission first':'ขออนุญาตก่อน','Stop — outside the task':'หยุด · อยู่นอกขอบเขตงาน','Approve this send':'อนุญาตให้ส่งครั้งนี้','Decline sending':'ไม่อนุญาตให้ส่ง','Limit it to saving a draft':'อนุญาตเพียงบันทึกเป็นฉบับร่าง','Send this reminder?':'ส่งข้อความเตือนนี้หรือไม่?','To':'ถึง','Message':'ข้อความ','Effect':'ผลของการดำเนินการ',
 'Within scope':'อยู่ในขอบเขต','Permission required':'ต้องขออนุญาต','Stopped':'หยุดแล้ว','Your permission decision':'การตัดสินใจของคุณ','Simulated delivery':'จำลองการส่ง','Not sent':'ไม่ได้ส่ง','Draft only':'ฉบับร่างเท่านั้น','Sending declined':'ไม่อนุญาตให้ส่ง','One simulated send approved':'อนุญาตการส่งจำลอง 1 ครั้ง','Permission limited to a draft':'อนุญาตเฉพาะฉบับร่าง','Exercise complete ✓':'ทำแบบฝึกหัดเสร็จแล้ว ✓','At the Permission Door':'ถึงประตูขออนุญาตแล้ว','Heading to the Permission Door…':'กำลังไปที่ประตูขออนุญาต…','Continue with the exercise':'ทำแบบฝึกหัดต่อได้','Opening the practice office…':'กำลังเปิดห้องฝึก…','Lesson animation · separate from live tasks':'ภาพเคลื่อนไหวในบทเรียน · แยกจากงานจริง',
 'Return Kubo to center':'ให้ Kubo กลับจุดเริ่มต้น','Your decision · simulated permission':'การตัดสินใจของคุณ · การอนุญาตจำลอง','Mali, the fictional visitor':'มะลิ ผู้มาติดต่อสมมติ',
 'Working rooms':'ห้องทำงาน','One room per local task':'หนึ่งห้องต่อหนึ่งงานบนเครื่องนี้','Agentic Dashboard':'ห้องทำงาน Agentic AI','Customize':'ปรับแต่ง','Connected':'เชื่อมต่อแล้ว','Disconnected':'ไม่ได้เชื่อมต่อ','Visual demo':'ตัวอย่างภาพจำลอง','Colors':'สี','Color theme':'ชุดสี','Warm cream':'ครีมอบอุ่น','Soft mint':'มินต์อ่อน','Lilac pastel':'ม่วงพาสเทล','Outfit':'ชุด','Face':'สีหน้า','Classic office':'ชุดทำงานเดิม','Mint overalls':'เอี๊ยมสีมินต์','Rose pinafore':'ชุดกระโปรงสีชมพู','Lilac hijab + pinafore':'ฮิญาบม่วงและชุดกระโปรง','Automatic':'อัตโนมัติ','Angry':'โกรธ','Tired':'เหนื่อย','Sad':'เศร้า','Motivated':'มุ่งมั่น',
 'No recent update':'ไม่มีข้อมูลอัปเดตล่าสุด','Active':'กำลังทำงาน','Needs input':'ต้องการข้อมูลจากคุณ','Turn completed':'ทำงานรอบนี้เสร็จแล้ว','Interrupted':'ถูกขัดจังหวะ','No recent event':'ไม่มีเหตุการณ์ล่าสุด','Show hidden offices':'แสดงห้องที่ซ่อนไว้','No offices to show. A task will appear when it starts.':'ยังไม่มีห้องให้แสดง เมื่อเริ่มงาน ห้องจะปรากฏขึ้น','Live workspace':'ห้องแสดงการทำงานจริง','Live task · locked':'ติดตามงานจริง · ล็อกอยู่','Following live':'กำลังติดตามงานจริง','Resume live':'กลับไปติดตามงานจริง','Live task':'งานจริง','Current step':'ขั้นตอนปัจจุบัน','Updates disconnected':'การอัปเดตขาดการเชื่อมต่อ','Task records unavailable':'ไม่พบข้อมูลบันทึกงาน','Wrapping up':'กำลังสรุปงาน','Opening the room…':'กำลังเปิดห้อง…','Reload':'โหลดใหม่','Idle':'พร้อมทำงาน','Running':'กำลังวิ่ง','Turning':'กำลังหันตัว','Working animation':'ท่าทางทำงาน','Waiting animation':'ท่าทางรอ','Ready in this room':'พร้อมอยู่ในห้องนี้',
 'Context Desk':'โต๊ะอ่านบริบท','Safe':'ตู้เก็บกฎ','Shortcut':'ปุ่มลัด','Skill Files':'ชั้นคู่มือ','Helper Station':'โต๊ะตรวจงาน','Permission Door':'ประตูขออนุญาต','Document Intake':'จุดรับเอกสาร','Task Board':'กระดานงาน','KUBO':'KUBO','TRY IT OUT':'ลองใช้งาน','CURRENT ACTIVITY':'กิจกรรมปัจจุบัน','View task details':'ดูรายละเอียดงาน','Explore the stations':'สำรวจจุดทำงาน','Stations':'จุดทำงาน','Task rooms':'ห้องของแต่ละงาน','Interactive office':'ห้องทำงานแบบโต้ตอบ','Reset camera view':'คืนมุมกล้องเริ่มต้น','Drag to look around · Pinch or scroll to zoom':'ลากเพื่อหมุนมุมมอง · จีบหน้าจอหรือเลื่อนเพื่อซูม',
 'Your AI agent reviews your request and works at the computer.':'เอเจนต์ AI อ่านคำขอของคุณและทำงานที่คอมพิวเตอร์','Your AI agent checks the rules for your project.':'เอเจนต์ AI ตรวจดูกฎของโครงการ','Your AI agent chooses the right instructions for the job.':'เอเจนต์ AI เลือกคำแนะนำที่เหมาะกับงาน','Your AI agent reads helpful guides and reference files.':'เอเจนต์ AI อ่านคู่มือและเอกสารอ้างอิง','Your AI agent checks the work for mistakes.':'เอเจนต์ AI ตรวจหาข้อผิดพลาดในงาน','Your AI agent needs your permission before continuing.':'เอเจนต์ AI ต้องขออนุญาตคุณก่อนทำต่อ','Your AI agent gathers and organizes the files it needs.':'เอเจนต์ AI รวบรวมและจัดระเบียบไฟล์ที่จำเป็น','Your AI agent plans the work and summarizes what is ready.':'เอเจนต์ AI วางแผนและสรุปสิ่งที่ทำเสร็จแล้ว',
 'Playful run':'วิ่งอย่างร่าเริง','Sitting down':'กำลังนั่งลง','Standing up':'กำลังลุกขึ้น','Typing':'กำลังพิมพ์','Reading the screen':'กำลังอ่านหน้าจอ','Pressing the shortcut':'กำลังกดปุ่มลัด','Reading a file':'กำลังอ่านไฟล์','Checking documents':'กำลังตรวจเอกสาร','Sorting documents':'กำลังจัดเอกสาร','Updating the board':'กำลังอัปเดตกระดาน','Inspecting the safe':'กำลังตรวจตู้เก็บกฎ','Waiting at the door':'กำลังรอที่ประตู','Task received':'ได้รับงานแล้ว','Celebrate':'ดีใจที่ทำเสร็จ','Concerned':'กังวล','Approval granted':'ได้รับอนุญาตแล้ว','Approval denied':'ไม่ได้รับอนุญาต','Walk':'เดิน','Thinking…':'กำลังคิด…','Thinking':'กำลังคิด','Ready to explore.':'พร้อมสำรวจแล้ว','Explore preview':'ตัวอย่างการสำรวจ','Animation preview':'ตัวอย่างท่าทาง','Hi there! 👋':'สวัสดี! 👋',
 ...THAI_LESSONS,
};
const normalize=s=>s.replace(/\s+/g,' ').trim();
const lookup=new Map(Object.entries(THAI).map(([en,th])=>[normalize(en),th]));
const sentences=[...lookup.keys()].filter(s=>/[.!?]$/.test(s)).sort((a,b)=>b.length-a.length);
export function translate(text,language='th'){
 if(language!=='th'||typeof text!=='string'||!text.trim())return text;
 const key=normalize(text);const exact=lookup.get(key);if(exact)return exact;
 const patterns=[
 [/^(\d+) spaces? · add$/,m=>`${m[1]} ช่อง · เพิ่ม`],[/^(\d+) \/ (\d+) spaces$/,m=>`${m[1]} / ${m[2]} ช่อง`],[/^(\d+) of 4 blocks$/,m=>`${m[1]} จาก 4 ส่วน`],
 [/^(\d+) redirecting passages? (?:is|are) unmarked; (\d+) ordinary passages? (?:was|were) marked\. Adjust your choices and check again\.$/,m=>`ยังไม่ได้ทำเครื่องหมายคำสั่งแฝง ${m[1]} ส่วน และทำเครื่องหมายข้อมูลทั่วไปไป ${m[2]} ส่วน ลองปรับแล้วตรวจอีกครั้ง`],
 [/^(English|Thai): (\d+)$/,m=>`${m[1]==='Thai'?'ไทย':'อังกฤษ'}: ${m[2]}`],
 [/^(English|Thai) text plus reserved answer space$/,m=>`ข้อความ${m[1]==='Thai'?'ไทย':'อังกฤษ'}รวมพื้นที่เผื่อคำตอบ`],
 [/^(\d+) input tokens plus (\d+) reserved, out of (\d+)$/,m=>`ข้อความ ${m[1]} โทเคน บวกพื้นที่เผื่อ ${m[2]} จากทั้งหมด ${m[3]}`],
 [/^Last reported activity: (.*?)\. Progress appears only when the task reports it\.$/,m=>`กิจกรรมที่รายงานล่าสุด: ${translate(m[1])} ความคืบหน้าจะแสดงเมื่องานรายงานเข้ามา`],
 [/^Hide office: (.*)$/,m=>`ซ่อนห้อง: ${m[1]}`],
 [/^(\d+) of 4 methods tried(.*)$/,m=>`ลองแล้ว ${m[1]} จาก 4 วิธี${m[2]?' · ลองเขียนข้อความเตือนได้เลย!':''}`],
 [/^Action (\d+) of 4$/,m=>`การดำเนินการที่ ${m[1]} จาก 4`],[/^Current context · (\d+) cards$/,m=>`บริบทปัจจุบัน · ${m[1]} ใบ`],
 [/^Your instructions · (\d+) of 4 blocks$/,m=>`คำสั่งของคุณ · ${m[1]} จาก 4 ส่วน`],[/^YOUR VERSION · (\d+) BLOCKS$/,m=>`คำสั่งของคุณ · ${m[1]} ส่วน`],
 [/^(\d+) passages marked for review$/,m=>`ทำเครื่องหมายเพื่อตรวจสอบ ${m[1]} ส่วน`],
 [/^(\d+) characters · maximum 1600$/,m=>`${m[1]} อักขระ · สูงสุด 1600`],[/^(\d+) tokens$/,m=>`${m[1]} โทเคน`],
 [/^(\d+) tokens (left in|over) this practice limit$/,m=>m[2]==='over'?`เกินขีดจำกัดฝึก ${m[1]} โทเคน`:`เหลือ ${m[1]} โทเคนในขีดจำกัดฝึกนี้`],
 [/^(\d+) input \+ (\d+) reserved =$/,m=>`ข้อความ ${m[1]} + สำรอง ${m[2]} =`],
 [/^Try again\. (.*)$/,m=>`ลองอีกครั้ง ${translate(m[1])}`],[/^Remove (.*) block$/,m=>`นำส่วน${translate(m[1])}ออก`],[/^Remove (.*)$/,m=>`นำ${translate(m[1])}ออก`],
 [/^([1-8])\.? (.+)$/,m=>`${m[1]}. ${translate(m[2])}`],[/^(.*) · Tried ✓$/,m=>`${translate(m[1])} · ลองแล้ว ✓`],
 [/^On my way to (.*)\.$/,m=>`กำลังไปที่${translate(m[1])}`],[/^Preview: (.*)\.$/,m=>`ตัวอย่าง: ${translate(m[1][0].toUpperCase()+m[1].slice(1))}`],
 [/^(\d+)s ago$/,m=>`${m[1]} วินาทีที่แล้ว`],
 ];
 for(const [pattern,fn] of patterns){const match=key.match(pattern);if(match)return fn(match);}
 if(text.includes('\n'))return text.split('\n').map(s=>translate(s)).join('\n');
 for(const sentence of sentences)if(key.startsWith(sentence+' '))return lookup.get(sentence)+' '+translate(key.slice(sentence.length+1));
 // Compose labels and complete known sentences without altering IDs, inputs or logic.
 for(const sep of [' · ',' ×'])if(key.includes(sep))return key.split(sep).map(s=>translate(s)).join(sep);
 if(key.startsWith('“')&&key.endsWith('”'))return '“'+translate(key.slice(1,-1))+'”';
 return text;
}
